source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KidJson_Example', :exclusive => true do
  pod 'KidJson', :path => '../'
end

target 'KidJson_Tests', :exclusive => true do
  pod 'KidJson', :path => '../'

  
end
